version: "3.7"

services:
  app: &defaults
    image: node:14-alpine3.12
    working_dir: /app
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - 8888:8888
    depends_on:
      - redis
      - memcache
      - dynamodb
  #the services below is a short hand to use npm in docker context
  test:
    <<: *defaults
    command: npm run test

  redis:
    image: redis
    ports:
      - 6379:6379

  memcache:
    image: memcached:1.4.21
    ports:
      - 11211:11211

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"



  lint:
    build:
      context: .
    command: npm run lint
    volumes:
      - .:/app
  format:
    build:
      context: .
    command: npm run format
    volumes:
      - .:/app

networks:
  default:
    name: gritzkoo-nodejs-health-checker
